baseURL: "https://jchgu.rbind.io" 
title: Jiancheng Gu
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Resources
          url: resources/
          weight: 2

params:
    description: |
      PhD Researcher in Migration Studies
    author: Jiancheng Gu
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "November 2023"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jiancheng Gu
          subtitle: |
            Welcome to my website! I am a PhD Researcher at the
            [Department for Migration and Globalisation,](https://www.donau-uni.ac.at/en/university/faculties/business-globalization/departments/migration-globalization.html)
            [Universität für Weiterbildung Krems.](https://www.donau-uni.ac.at/en/)
            My research interests include quantitative migration studies, causal inference, and open science.
            I work within the Horizon Europe project [Finding Agreement in Return (FAiR),](https://www.youtube.com/watch?v=A264XtpcQaY)
            studying the policy outcomes on irregular migration and return.
            
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Jiancheng Gu
          buttons:
            - name: Research
              url: research/
            - name: Resources
              url: resources/
            - name: Tags
              url: tags/
    socialIcons:
        - name: CV
          url: CV_Gu.pdf
        - name: Email
          url: mailto:jiancheng.gu@donau-uni.ac.at
        - name: orcid
          url: https://orcid.org/0009-0002-3033-6472
        - name: GitHub
          url: https://github.com/jchgu

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jiancheng Gu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2